// Generated by GG/scripts/sync-game-menus.mjs.
export const GAME_MENU = {
  "selector": "[data-gg-pregame]",
  "steps": {
    "en": [
      "Find the player who does not know the secret location.",
      "Ask and answer questions without revealing the location directly.",
      "Listen for inconsistent answers, then vote for the suspected mole."
    ],
    "ru": [
      "Найди игрока, который не знает секретную локацию.",
      "Задавай вопросы и отвечай, не называя место напрямую.",
      "Замечай противоречия в ответах и голосуй за предполагаемого крота."
    ]
  }
}
