// English translations keyed by the exact Russian source string.
// Russian stays the default; these are used when the language is switched to 'en'.
export const EN: Record<string, string> = {
  // Приглашение друзей из хаба (screens/HubInvite.tsx)
  'Позвать друзей из хаба': 'Invite friends from the hub',
  'Позвать': 'Invite',
  'Позвали': 'Invited',
  'Позвать всех': 'Invite everyone',
  // ── Brand / App ─────────────────────────────────────────────────────────
  'Крот': 'The Mole',
  'Заводим разговор': 'Starting the conversation',
  'Один из вас тут чужой. Задавайте вопросы и найдите крота.':
    'One of you is an outsider. Ask questions and find the mole.',

  // ── Home ────────────────────────────────────────────────────────────────
  'Звук': 'Sound',
  'Победы': 'Wins',
  'Серия': 'Streak',
  'Монеты': 'Coins',
  'Быстрая игра': 'Quick match',
  'Случайный стол прямо сейчас': 'A random table right now',
  'Соло': 'Solo',
  'Партия против ботов, три уровня': 'A game against bots, three levels',
  'Игра с друзьями': 'Play with friends',
  'Собери стол и поделись кодом': 'Gather a table and share the code',
  'Зайти по коду': 'Join by code',
  'Введи код из четырёх символов': 'Enter a four-character code',
  'Рейтинг': 'Leaderboard',
  'Правила': 'Rules',

  // ── Setup sheet (App.tsx) ───────────────────────────────────────────────
  'Соло против ботов': 'Solo vs bots',
  'Выбери набор и сложность.': 'Pick a pack and difficulty.',
  'Выбери набор и сложность, потом позовёшь друзей.':
    'Pick a pack and difficulty, then invite your friends.',
  'Набор локаций': 'Location pack',
  'Сложность ботов': 'Bot difficulty',
  'Накрываем стол…': 'Setting the table…',
  'Начать 🕵️': 'Start 🕵️',
  'Создать стол 🕵️': 'Create a table 🕵️',

  // ── Result modal reasons (App.tsx) ──────────────────────────────────────
  'Крота вычислили и вывели на чистую воду.': 'The mole was found out and exposed.',
  'Тебя раскусили. Стол оказался зорче.': 'You were rumbled. The table was sharper.',
  'Стол выгнал своего, а крот тихо остался.':
    'The table booted one of its own while the mole quietly stayed.',
  'Город выгнал невиновного. Крот ускользнул.':
    'The town ousted an innocent. The mole slipped away.',
  'Стол так и не договорился, крот ушёл в тень.':
    'The table never agreed, and the mole faded into the shadows.',
  'Никто не сошёлся во мнении, и ты улизнул.':
    'Nobody could agree, and you got away.',
  'Крот вслушался и точно назвал локацию.':
    'The mole listened closely and named the location exactly.',
  'Ты вычислил место и забрал победу!': 'You figured out the place and took the win!',
  'Крот промахнулся с локацией и выдал себя.':
    'The mole guessed the wrong location and gave themselves away.',
  'Локация оказалась не та. Обидно.': 'Wrong location. Tough luck.',

  // ── Result modal (App.tsx) ──────────────────────────────────────────────
  'Ты на стороне победителей.': "You're on the winning side.",
  'В этот раз победил крот.': 'This time the mole won.',
  'В этот раз победил город.': 'This time the town won.',
  'Победа': 'Victory',
  'Поражение': 'Defeat',
  'Кротом был': 'The mole was',
  'Ты': 'You',
  'Локация': 'Location',
  'Ещё партию 🕵️': 'One more round 🕵️',
  'Играть снова 🕵️': 'Play again 🕵️',
  'На главную': 'Home',

  // ── Store toasts / errors ───────────────────────────────────────────────
  'Нет комнаты с таким кодом.': 'No room with that code.',
  'Игра уже началась.': 'The game has already started.',
  'В комнате нет мест.': 'The room is full.',
  'Код из четырёх символов.': 'The code is four characters.',
  'Не получилось, попробуй ещё раз.': "That didn't work, try again.",
  'Не удалось начать игру. Проверь связь.': "Couldn't start the game. Check your connection.",
  'Не удалось подобрать игру. Проверь связь.': "Couldn't find a match. Check your connection.",
  'Не удалось создать комнату. Проверь связь.': "Couldn't create the room. Check your connection.",
  'Не удалось войти.': "Couldn't join.",
  'Нужно хотя бы трое игроков.': 'You need at least three players.',
  'Не удалось начать.': "Couldn't start.",
  'Сейчас не твой ход.': "It's not your turn right now.",

  // ── Lobby ───────────────────────────────────────────────────────────────
  'КОД': 'CODE',
  'Заходим…': 'Joining…',
  'Войти в игру': 'Enter the game',
  'Стол собирается': 'Gathering the table',
  'Поделись этим кодом': 'Share this code',
  'Позвать друзей ↗': 'Invite friends ↗',
  'мест': 'places',
  'монет': 'coins',
  'Сыграй со мной в «Крота»! Код стола': 'Play "The Mole" with me! Table code',
  'Заполнить пустые места до стола из': 'Fill empty seats to make a table of',
  'Пустые места займут боты, когда начнёшь. Стол из':
    'Bots will take the empty seats when you start. A table of',
  'Играете своей компанией. Сейчас за столом:':
    'Playing with your own crew. At the table now:',
  'ХОЗЯИН': 'HOST',
  'БОТ': 'BOT',
  'ГОТОВ': 'READY',
  'Ждём друзей': 'Waiting for friends',
  'Добавить ботов': 'Add bots',
  'Набор и сложность': 'Pack and difficulty',
  'Ждём, пока хозяин начнёт': 'Waiting for the host to start',
  'Начать игру 🕵️': 'Start the game 🕵️',

  // ── Game screen ─────────────────────────────────────────────────────────
  'Выйти': 'Leave',
  'Голосование': 'Voting',
  'Круг': 'Round',
  'из 2': 'of 2',
  'из': 'of',
  'ты': 'you',
  'Кто': 'Who is the',
  'крот': 'mole',
  'Кого': 'Who to',
  'Нужно хотя бы трое.': 'You need at least three.',
  '🕵️ Крот': '🕵️ Mole',
  'Допрос начинается. По очереди задавайте друг другу вопросы и слушайте ответы.':
    'The interrogation begins. Take turns asking each other questions and listen to the answers.',
  'Голос принят. Ждём остальных': 'Vote recorded. Waiting for the others',
  'Кто из них крот? Голосуй.': 'Which of them is the mole? Vote.',
  'спрашивает тебя': 'is asking you',
  'отвечает': 'is answering',
  'Твой ход. Спроси кого-нибудь.': 'Your turn. Ask someone.',
  'Спрашивает': 'Asking',
  'Воздержаться': 'Abstain',
  'Можно передумать, пока считают голоса.': 'You can change your mind while votes are counted.',
  'допросить': 'interrogate',
  '📋 Локации': '📋 Locations',
  '🎯 Локация': '🎯 Location',
  '🗳 Голосование': '🗳 Vote',
  'Возможные локации': 'Possible locations',
  'Где все собрались? Вычисли по ответам.': 'Where is everyone? Work it out from the answers.',
  'По этому списку удобно придумывать вопросы.': 'This list makes it easy to come up with questions.',
  'Закрыть': 'Close',
  'Назвать локацию': 'Name the location',
  'Угадаешь, забираешь победу. Промахнёшься, победит город.':
    'Guess right and take the win. Miss and the town wins.',
  'Назад': 'Back',
  'Это здесь!': "It's here!",
  'Спросить': 'Ask',
  'Выбери вопрос. Слушай, как ответят.': 'Pick a question. Listen to how they answer.',

  // ── Rules ───────────────────────────────────────────────────────────────
  'Как играть': 'How to play',
  'Попробовать 🕵️': 'Try it 🕵️',
  'Все знают место. Кроме одного': 'Everyone knows the place. Except one',
  'В начале партии все видят общую локацию и свою роль на ней. Один игрок крот: он не знает, где все собрались.':
    'At the start, everyone sees the shared location and their role in it. One player is the mole: they have no idea where everyone gathered.',
  'Допрос по кругу': 'Interrogation in a circle',
  'По очереди задавайте друг другу по одному короткому вопросу. Часто ли тут бываешь, чем пахнет, во что одет. Слушайте, как отвечают.':
    'Take turns asking each other one short question. Do you come here often, what does it smell like, what are you wearing. Listen to how they answer.',
  'Свой отвечает по делу': 'Insiders answer to the point',
  'Город отвечает уверенно, но вслух локацию не называет, иначе крот её услышит. Крот юлит и подыгрывает, ведь места он не знает.':
    "The town answers confidently but never says the location out loud, or the mole will hear it. The mole hedges and plays along, since they don't know the place.",
  'Любой может созвать голосование. Выбрали крота, побеждает город. Выгнали невиновного или стол не договорился, побеждает крот.':
    "Anyone can call a vote. Pick the mole and the town wins. Oust an innocent, or fail to agree, and the mole wins.",
  'Догадка крота': "The mole's guess",
  'Крот может в любой момент назвать локацию. Угадал, победа крота. Промахнулся, победа города.':
    'The mole can name the location at any time. Right guess, mole wins. Wrong guess, town wins.',
  'Список локаций': 'Location list',
  'Возможные локации видны всем. По ним удобно придумывать вопросы, и по ним же крот гадает, где оказался.':
    'The possible locations are visible to everyone. They help you think up questions, and the mole uses them to guess where they landed.',

  // ── Leaderboard ─────────────────────────────────────────────────────────
  'Пока никто не сыграл ни партии.': 'Nobody has played a round yet.',
  'Будь первым за столом 🕵️': 'Be the first at the table 🕵️',

  // ── RoleCard ────────────────────────────────────────────────────────────
  'Тайная личность': 'Secret identity',
  'ТЫ КРОТ': 'YOU ARE THE MOLE',
  'Локацию ты не знаешь. Слушай, о чём говорят, отвечай уклончиво и не выдай себя. Поймёшь, где все собрались, нажми «Назвать локацию» и забери победу.':
    'You don\'t know the location. Listen to what they talk about, answer evasively, and don\'t give yourself away. Once you figure out where everyone gathered, tap "Name the location" and take the win.',
  'Твоя роль': 'Your role',
  'Отвечай так, чтобы было ясно: ты тут свой. Но вслух локацию не называй, иначе крот её услышит.':
    "Answer so it's clear you belong here. But don't say the location out loud, or the mole will hear it.",
  'Ждём остальных': 'Waiting for the others',
  'Затаиться 🕵️': 'Lie low 🕵️',
  'Я готов': "I'm ready",

  // ── Difficulty (difficulty.ts) ──────────────────────────────────────────
  'Новичок': 'Rookie',
  'Легко ведётся': 'Easily fooled',
  'Знаток': 'Sharp',
  'Держит нить': 'Follows the thread',
  'Мастер': 'Master',
  'Видит насквозь': 'Sees right through you',

  // ── Packs (locations.ts) ────────────────────────────────────────────────
  'Классика': 'Classic',
  'Узнаваемые места': 'Familiar places',
  'Путешествия': 'Travel',
  'Дорога и приключения': 'Roads and adventures',
  'Особые': 'Special',
  'Необычные сцены': 'Unusual scenes',
  'Всё': 'All',
  'Все локации сразу': 'Every location at once',

  // ── Locations (locations.ts) ────────────────────────────────────────────
  'Казино': 'Casino',
  'Больница': 'Hospital',
  'Школа': 'School',
  'Ресторан': 'Restaurant',
  'Банк': 'Bank',
  'Супермаркет': 'Supermarket',
  'Пожарная часть': 'Fire station',
  'Пляж': 'Beach',
  'Киностудия': 'Film studio',
  'Парк аттракционов': 'Amusement park',
  'Самолёт': 'Airplane',
  'Поезд': 'Train',
  'Круизный лайнер': 'Cruise ship',
  'Отель': 'Hotel',
  'Горный курорт': 'Mountain resort',
  'Турлагерь': 'Camping trip',
  'Космическая станция': 'Space station',
  'Караван в пустыне': 'Desert caravan',
  'Раскопки': 'Excavation site',
  'Подводная лодка': 'Submarine',
  'Цирк': 'Circus',
  'Театр': 'Theater',
  'Средневековый замок': 'Medieval castle',
  'Резиденция разведки': 'Intelligence HQ',
  'Секретная лаборатория': 'Secret laboratory',
  'Симфонический оркестр': 'Symphony orchestra',
  'Стадион': 'Stadium',
  'Музей': 'Museum',
  'Свадьба': 'Wedding',
  'Монастырь': 'Monastery',

  // ── Roles (locations.ts) ────────────────────────────────────────────────
  // Casino
  'Крупье': 'Croupier',
  'Охранник': 'Security guard',
  'Бармен': 'Bartender',
  'Шулер': 'Card sharp',
  'Хозяин': 'Owner',
  'Официантка': 'Waitress',
  'Завсегдатай': 'Regular',
  // Hospital
  'Хирург': 'Surgeon',
  'Медсестра': 'Nurse',
  'Пациент': 'Patient',
  'Анестезиолог': 'Anesthetist',
  'Практикант': 'Intern',
  'Санитар': 'Orderly',
  'Посетитель': 'Visitor',
  // School
  'Учитель': 'Teacher',
  'Директор': 'Principal',
  'Двоечник': 'Failing student',
  'Отличница': 'Straight-A student',
  'Завуч': 'Vice-principal',
  'Уборщица': 'Cleaning lady',
  'Физрук': 'PE teacher',
  // Restaurant
  'Шеф-повар': 'Head chef',
  'Официант': 'Waiter',
  'Метрдотель': 'Maître d\'',
  'Сомелье': 'Sommelier',
  'Гость': 'Guest',
  'Посудомойщик': 'Dishwasher',
  'Критик': 'Critic',
  // Bank
  'Кассир': 'Teller',
  'Управляющий': 'Manager',
  'Инкассатор': 'Cash courier',
  'Клиент': 'Client',
  'Стажёр': 'Trainee',
  'Грабитель': 'Robber',
  // Supermarket
  'Мерчендайзер': 'Merchandiser',
  'Грузчик': 'Loader',
  'Покупатель': 'Shopper',
  'Администратор': 'Manager on duty',
  'Промоутер': 'Promoter',
  // Fire station
  'Брандмейстер': 'Fire chief',
  'Пожарный': 'Firefighter',
  'Диспетчер': 'Dispatcher',
  'Водитель': 'Driver',
  'Механик': 'Mechanic',
  'Доброволец': 'Volunteer',
  // Beach
  'Спасатель': 'Lifeguard',
  'Загорающий': 'Sunbather',
  'Сёрфингист': 'Surfer',
  'Продавец мороженого': 'Ice cream vendor',
  'Тренер': 'Coach',
  'Турист': 'Tourist',
  'Аниматор': 'Entertainer',
  // Film studio
  'Режиссёр': 'Director',
  'Актёр': 'Actor',
  'Каскадёр': 'Stuntman',
  'Гримёр': 'Makeup artist',
  'Оператор': 'Cameraman',
  'Сценарист': 'Screenwriter',
  'Статист': 'Extra',
  // Amusement park
  'Зазывала': 'Barker',
  'Оператор карусели': 'Ride operator',
  'Уборщик': 'Janitor',
  'Ростовая кукла': 'Mascot',
  'Фокусник': 'Magician',
  // Airplane
  'Командир': 'Captain',
  'Стюардесса': 'Flight attendant',
  'Пассажир': 'Passenger',
  'Второй пилот': 'Co-pilot',
  'Бортпроводник': 'Cabin crew',
  'Безбилетник': 'Stowaway',
  'Авиамеханик': 'Aircraft mechanic',
  // Train
  'Машинист': 'Engine driver',
  'Проводник': 'Conductor',
  'Контролёр': 'Ticket inspector',
  'Бригадир': 'Train chief',
  'Буфетчик': 'Buffet attendant',
  // Cruise ship
  'Капитан': 'Captain',
  'Стюард': 'Steward',
  'Штурман': 'Navigator',
  'Кок': 'Ship\'s cook',
  'Музыкант': 'Musician',
  // Hotel
  'Портье': 'Front desk clerk',
  'Горничная': 'Housemaid',
  'Постоялец': 'Lodger',
  'Швейцар': 'Doorman',
  'Консьерж': 'Concierge',
  'Повар': 'Cook',
  // Mountain resort
  'Инструктор': 'Instructor',
  'Лыжник': 'Skier',
  'Бариста': 'Barista',
  'Сноубордист': 'Snowboarder',
  'Водитель ратрака': 'Snowcat driver',
  // Camping trip
  'Вожатый': 'Camp leader',
  'Егерь': 'Ranger',
  'Гитарист': 'Guitarist',
  'Рыбак': 'Fisherman',
  // Space station
  'Бортинженер': 'Flight engineer',
  'Учёный': 'Scientist',
  'Космотурист': 'Space tourist',
  'Робототехник': 'Roboticist',
  'Врач': 'Doctor',
  // Desert caravan
  'Торговец': 'Trader',
  'Погонщик': 'Camel driver',
  'Путник': 'Wanderer',
  'Картограф': 'Cartographer',
  'Сторож': 'Watchman',
  'Лекарь': 'Healer',
  // Excavation site
  'Профессор': 'Professor',
  'Студент': 'Student',
  'Рабочий': 'Laborer',
  'Реставратор': 'Restorer',
  'Спонсор': 'Sponsor',
  'Местный гид': 'Local guide',
  // Submarine
  'Старпом': 'First mate',
  'Акустик': 'Sonar operator',
  'Радист': 'Radio operator',
  'Новобранец': 'Recruit',
  // Circus
  'Дрессировщик': 'Animal tamer',
  'Клоун': 'Clown',
  'Акробат': 'Acrobat',
  'Зритель': 'Spectator',
  'Силач': 'Strongman',
  'Шпрехшталмейстер': 'Ringmaster',
  // Theater
  'Премьер': 'Lead actor',
  'Суфлёр': 'Prompter',
  'Костюмер': 'Costumer',
  'Билетёр': 'Usher',
  'Осветитель': 'Lighting tech',
  // Medieval castle
  'Король': 'King',
  'Рыцарь': 'Knight',
  'Шут': 'Jester',
  'Кузнец': 'Blacksmith',
  'Служанка': 'Maidservant',
  'Звездочёт': 'Astrologer',
  'Стражник': 'Guardsman',
  // Intelligence HQ
  'Резидент': 'Station chief',
  'Шифровальщик': 'Cryptographer',
  'Курьер': 'Courier',
  'Аналитик': 'Analyst',
  'Двойной агент': 'Double agent',
  'Архивариус': 'Archivist',
  // Secret laboratory
  'Лаборант': 'Lab assistant',
  'Подопытный': 'Test subject',
  'Инвестор': 'Investor',
  'Инженер': 'Engineer',
  // Symphony orchestra
  'Дирижёр': 'Conductor',
  'Скрипач': 'Violinist',
  'Литаврист': 'Timpanist',
  'Пианист': 'Pianist',
  'Слушатель': 'Listener',
  'Настройщик': 'Tuner',
  'Солист': 'Soloist',
  // Stadium
  'Нападающий': 'Striker',
  'Вратарь': 'Goalkeeper',
  'Судья': 'Referee',
  'Болельщик': 'Fan',
  'Комментатор': 'Commentator',
  'Массажист': 'Masseur',
  // Museum
  'Экскурсовод': 'Tour guide',
  'Смотритель': 'Warden',
  'Похититель': 'Thief',
  'Копиист': 'Copyist',
  // Wedding
  'Жених': 'Groom',
  'Невеста': 'Bride',
  'Тамада': 'Toastmaster',
  'Свидетель': 'Best man',
  'Фотограф': 'Photographer',
  'Тёща': 'Mother-in-law',
  'Диджей': 'DJ',
  // Monastery
  'Настоятель': 'Abbot',
  'Послушник': 'Novice',
  'Звонарь': 'Bell ringer',
  'Паломник': 'Pilgrim',
  'Иконописец': 'Icon painter',
  'Трапезник': 'Refectory keeper',
  'Садовник': 'Gardener',

  // ── Questions (interrogation.ts) ────────────────────────────────────────
  'Как ты сюда добрался?': 'How did you get here?',
  'Тебе тут вообще нравится?': 'Do you even like it here?',
  'Что у тебя сейчас в руках?': 'What are you holding right now?',
  'Часто здесь бываешь?': 'Do you come here often?',
  'Во что ты сегодня одет?': "What are you wearing today?",
  'Чем тут пахнет, по-твоему?': 'What does it smell like here, to you?',
  'Кто тут, по-твоему, главный?': "Who's in charge here, do you think?",
  'Что бы ты тут точно делать не стал?': "What would you definitely not do here?",
  'Сколько времени ты обычно тут проводишь?': 'How much time do you usually spend here?',
  'Тут шумно или тихо?': 'Is it noisy or quiet here?',
  'Тебе за это платят?': 'Do you get paid for this?',
  'Привёл бы сюда своего ребёнка?': 'Would you bring your kid here?',
  'Что первым бросается в глаза?': 'What catches your eye first?',
  'Тебе удобно в твоей одежде?': 'Are you comfortable in your clothes?',
  'Что бы ты тут перекусил?': 'What would you grab to eat here?',
  'Ты бы остался тут на ночь?': 'Would you stay here overnight?',
  'Можно тут расслабиться или надо быть начеку?':
    'Can you relax here, or do you need to stay alert?',
  'Давно ты в этом деле?': 'Have you been at this long?',

  // ── Town answers (interrogation.ts) ─────────────────────────────────────
  'Да я тут как у себя дома, привычное дело.': "I'm right at home here, business as usual.",
  'Конечно, бываю тут постоянно, по работе.': 'Sure, I\'m here all the time, for work.',
  'Нормально, мне тут спокойно и удобно.': "It's fine, I feel calm and comfortable here.",
  'А что такого, обычный для меня день.': "What's the big deal, just an ordinary day for me.",
  'Тут всё знакомо, глаза закрой и пройду.': 'Everything\'s familiar, I could walk it blindfolded.',
  'По долгу, так сказать, привык уже.': "It's my duty, so to speak, I'm used to it.",
  'Мне нравится, своя атмосфера тут.': 'I like it, there\'s a nice vibe here.',
  'Да я тут половину жизни провожу, считай.': 'I basically spend half my life here.',
  'Спокойно отвечу: всё на своих местах.': "I'll answer calmly: everything's in its place.",
  'Привычно, я бы даже сказал уютно.': "It's familiar, I'd even say cozy.",
  'Знаю тут каждый угол, чего скрывать.': "I know every corner here, no point hiding it.",
  'Тут как обычно, рабочая суета.': "It's the usual here, the daily bustle.",
  'Да нормально всё, занимаюсь своим делом.': "Everything's fine, just minding my business.",
  'Сразу видно, что я тут не впервые.': "You can tell right away I'm no first-timer here.",

  // ── Mole smooth answers (interrogation.ts) ──────────────────────────────
  'Ну, как и все тут, ничего особенного.': 'Well, like everyone else here, nothing special.',
  'Да в целом нормально, чего бы и нет.': 'Overall fine, why not.',
  'Как обычно, всё своим чередом.': 'As usual, everything in its own time.',
  'Смотря с чем сравнивать, но терпимо.': 'Depends what you compare it to, but bearable.',
  'Я бы не сказал, что как-то иначе, чем у других.':
    "I wouldn't say it's any different than for anyone else.",
  'Да всё в порядке, не на что жаловаться.': 'Everything\'s fine, nothing to complain about.',
  'Как у всех, наверное. А что?': 'Same as everyone, I guess. Why?',
  'Нормально, привыкаешь со временем.': "It's fine, you get used to it over time.",
  'Бывает по-разному, сегодня вот так.': 'It varies, today it\'s like this.',
  'Да обычное дело, чего тут расписывать.': "It's an ordinary thing, nothing to spell out.",
  'Я как все, не выделяюсь особо.': "I'm like everyone, nothing that stands out.",
  'Терпимо, могло быть и хуже.': 'Bearable, could be worse.',

  // ── Mole shaky answers (interrogation.ts) ───────────────────────────────
  'Эээ… ну, как тебе сказать…': 'Uhh… well, how do I put it…',
  'А почему ты именно у меня спрашиваешь?': 'Why are you asking me specifically?',
  'Да так, всё нормально вроде бы.': "Eh, everything's fine, I think.",
  'Хм, сложный вопрос, если честно.': "Hmm, tough question, honestly.",
  'Ну… по-всякому бывает, смотря когда.': 'Well… it depends, varies by the time.',
  'Не знаю, как-то не задумывался об этом.': "I don't know, never really thought about it.",
  'А сам ты как считаешь? Вот и я так же.': "What do you think? Same here.",
  'Да тут как везде, чего уж там.': "It's like anywhere else here, come on.",
  'Ой, ну это долго объяснять.': "Oh, that's a long story to explain.",
  'Давай я попозже отвечу, ладно?': "Let me answer later, okay?",

  // ── Inline human answer options (interrogation.ts) ──────────────────────
  'Да нормально, по-свойски тут.': "It's fine, feels like home here.",
  'Ха, а это секрет, не скажу.': "Ha, that's a secret, I won't tell.",
  'Да как и все, ничего необычного.': 'Same as everyone, nothing unusual.',

  // ── Bot names (names.ts) ────────────────────────────────────────────────
  'Маша': 'Masha',
  'Гриша': 'Grisha',
  'Нина': 'Nina',
  'Кирилл': 'Kirill',
  'Инна': 'Inna',
  'Артём': 'Artyom',
  'Дуся': 'Dusya',
  'Веня': 'Venya',
  'Фая': 'Faya',
  'Сёма': 'Syoma',
  'Гера': 'Gera',
  'Гоша': 'Gosha',
  'Вера': 'Vera',
  'Тимур': 'Timur',
  'Лиза': 'Liza',
  'Рома': 'Roma',
  // Quick-match names
  'Алексей': 'Alexei',
  'Дима': 'Dima',
  'Настя': 'Nastya',
  'Оля': 'Olya',
  'Саша': 'Sasha',
  'Макс': 'Max',
  'Катя': 'Katya',
  'Игорь': 'Igor',
  'Лена': 'Lena',
  'Паша': 'Pasha',
  'Юля': 'Yulya',
  'Костя': 'Kostya',
  'Соня': 'Sonya',
  'Андрей': 'Andrei',
  'Вика': 'Vika',
  'Никита': 'Nikita',

  // ── Language toggle label ───────────────────────────────────────────────
  'EN': 'RU',
}
